---
format: 
  revealjs:
    preview-links: auto
    code-link: true
    highlight-style: a11y
    chalkboard: true
    theme: 
      - meds_styles.scss
---

## {#run-cells data-menu-title="Run cells"}

<div class = "slide-title">`r fontawesome::fa("play", fill = "#05859B", a11y = "sem")` Run cells</div>

::: {.panel-tabset}
## `r fontawesome::fa("apple", fill = "#053660", a11y = "sem")` Mac
:::: {.columns}
::: {.column width="50%"}
<br>
<center><iframe width="550" height="290" src="media/mp4/Jupyter_run_cells.mp4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></center>
:::
::: {.column width="50%"}
<br>
<br>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Run selected cell (either mode): `control` (or `command`) + `return`</div>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Run selected cell & move to next cell (either mode): `shift` + `return`</div>
:::
::::

## `r fontawesome::fa("windows", fill = "#053660", a11y = "sem")` Windows
:::: {.columns}
::: {.column width="50%"}
iframe
:::
::: {.column width="50%"}
<br>
<br>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Run selected cell (either mode): `control` + `enter`</div>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Run selected cell & move to next cell (either mode): `shift` + `enter`</div>
:::
::::
:::

---

## {#change-modes-cell-types data-menu-title="Change modes & cell types"}

<div class = "slide-title">`r fontawesome::fa("exchange-alt", fill = "#05859B", a11y = "sem")` Change modes, cell types, delete cells</div>

::: {.panel-tabset}
## `r fontawesome::fa("apple", fill = "#053660", a11y = "sem")` Mac
:::: {.columns}
::: {.column width="50%"}
<br>
<center><iframe width="550" height="290" src="media/mp4/Jupyter_switchmodes.mp4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></center>
:::
::: {.column width="50%"}
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Change cell type to *Markdown* (command mode): `M`</div>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Change cell type to *Code*: `Y` (command mode)</div>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Activate command mode: `esc`</div>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Activate edit mode: `esc`</div>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Delete cell (command mode): `DD`</div>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Undo delete cell (command mode): `Z`</div>
:::
::::

## `r fontawesome::fa("windows", fill = "#053660", a11y = "sem")` Windows
:::: {.columns}
::: {.column width="50%"}
iframe
:::
::: {.column width="50%"}
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Change cell type to *Markdown* (command mode): `M`</div>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Change cell type to *Code*: `Y` (command mode)</div>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Activate command mode: `esc`</div>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Activate edit mode: `esc`</div>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Delete cell (command mode): `DD`</div>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Undo delete cell (command mode): `Z`</div>
:::
::::
:::

---

## {#insert-select-cells data-menu-title="Inserting & selecting cells"}

<div class = "slide-title">`r fontawesome::fa("plus", fill = "#05859B", a11y = "sem")` Insert cells & select multiple cells</div>

::: {.panel-tabset}
## `r fontawesome::fa("apple", fill = "#053660", a11y = "sem")` Mac
:::: {.columns}
::: {.column width="50%"}
<br>
<center><iframe width="550" height="290" src="media/mp4/Jupyter_addCells_selectCells.mp4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></center>
:::
::: {.column width="50%"}
<br>
<br>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Insert cell above (command mode): `A`</div>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Insert cell below (command mode): `B`</div>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Select multiple cells (command mode): `shift` + up/down arrow</div>
:::
::::

## `r fontawesome::fa("windows", fill = "#053660", a11y = "sem")` Windows
:::: {.columns}
::: {.column width="50%"}
iframe
:::
::: {.column width="50%"}
<br>
<br>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Insert cell above (command mode): `A`</div>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Insert cell below (command mode): `B`</div>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Select multiple cells (command mode): `shift` + up/down arrow</div>
:::
::::
:::

---

## {#jupyter-command-palette data-menu-title="Jupyter Command Palette"}

<div class = "slide-title">Open Command Palette</div>

::: {.panel-tabset}
## `r fontawesome::fa("apple", fill = "#053660", a11y = "sem")` Mac
:::: {.columns}
::: {.column width="50%"}
<br>
<center><iframe width="550" height="290" src="media/mp4/Jupyter_commandPalette.mp4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></center>
:::
::: {.column width="50%"}
<br>
<br>
<br>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Open command palette: `command` + `shift` + `P`</div>
:::
::::

## `r fontawesome::fa("windows", fill = "#053660", a11y = "sem")` Windows
:::: {.columns}
::: {.column width="50%"}
iframe
:::
::: {.column width="50%"}
<br>
<br>
<br>
<div class = "body-text">`r fontawesome::fa("angle-right", fill = "#05859B", a11y = "sem")` Open command palette: `control` + `shift` + `P`</div>
:::
::::
:::
